#!/usr/bin/env node
// scripts/import-leads.mjs — build api/_leads.mjs from the slugged lead CSV (item 10).
//
// Usage:
//     node scripts/import-leads.mjs agent_leads_with_slugs.csv
//
// The CSV's `Slug` column is the unique key. Column → record-key mapping:
//   Firm → company, Website → url, Town → town, First Name → first_name,
//   Phone → phone, Probe Address → probe_address, Probe Sent → probe_sent,
//   Listing URL → listing_url. Outreach-tracking columns are ignored.
//
// Re-run any time the CSV changes (including after probe_address / probe_sent are
// filled in per row) to refresh the lookup table.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../api/_leads.mjs');

const csvPath = process.argv[2];
if (!csvPath) {
  console.error('Usage: node scripts/import-leads.mjs <path-to-csv>');
  process.exit(1);
}

// Minimal RFC-4180-ish CSV parser (handles quoted fields, commas, escaped quotes, CRLF).
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field); field = '';
    } else if (c === '\n') {
      row.push(field); rows.push(row); row = []; field = '';
    } else if (c === '\r') {
      // swallow — handled by the following \n
    } else field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.some(v => v !== ''));
}

// Normalise a header cell to a comparable key.
const norm = (s) => s.trim().toLowerCase().replace(/\s+/g, ' ');

// Header label → record key.
const MAP = {
  'slug': 'slug',
  'firm': 'company',
  'website': 'url',
  'town': 'town',
  'first name': 'first_name',
  'phone': 'phone',
  'probe address': 'probe_address',
  'probe sent': 'probe_sent',
  'listing url': 'listing_url'
};

const raw = readFileSync(resolve(process.cwd(), csvPath), 'utf8');
const rows = parseCSV(raw);
if (!rows.length) { console.error('Empty CSV'); process.exit(1); }

const header = rows[0].map(norm);
const idx = {};
for (const [label, key] of Object.entries(MAP)) {
  const i = header.indexOf(label);
  if (i !== -1) idx[key] = i;
}
if (idx.slug == null) { console.error('CSV has no "Slug" column'); process.exit(1); }

const leads = {};
let skipped = 0;
for (let r = 1; r < rows.length; r++) {
  const cells = rows[r];
  const slug = (cells[idx.slug] || '').trim().toLowerCase();
  if (!slug) { skipped++; continue; }
  const get = (k) => (idx[k] != null ? (cells[idx[k]] || '').trim() : '');
  leads[slug] = {
    company:       get('company'),
    url:           get('url'),
    town:          get('town'),
    first_name:    get('first_name'),
    phone:         get('phone'),
    probe_address: get('probe_address'),
    probe_sent:    get('probe_sent'),
    listing_url:   get('listing_url')
  };
}

const banner = `// api/_leads.mjs — GENERATED by scripts/import-leads.mjs. Do not edit by hand.
// Source: ${csvPath}  ·  Generated: ${new Date().toISOString()}
// ${Object.keys(leads).length} leads. Re-run the import to refresh (e.g. after probing).
// Vercel does not route or statically serve _-prefixed files in /api, so phone /
// outreach columns here stay server-side; /api/lead exposes page fields only.
`;

writeFileSync(OUT, banner + '\nexport const LEADS = ' + JSON.stringify(leads, null, 2) + ';\n\nexport default LEADS;\n');
console.log(`Wrote ${Object.keys(leads).length} leads to ${OUT}${skipped ? ` (${skipped} rows skipped: no slug)` : ''}`);
