// api/_leads.mjs — GENERATED by scripts/import-leads.mjs. Do not edit by hand.
// Source: agent_leads_with_slugs.csv  ·  Generated: 2026-08-10T15:12:31.846Z
// 144 leads. Re-run the import to refresh (e.g. after probing).
// Vercel does not route or statically serve _-prefixed files in /api, so phone /
// outreach columns here stay server-side; /api/lead exposes page fields only.

export const LEADS = {
  // ═══════════════════════════════════════════════════════════════════════
  // TEMPORARY DEV-ONLY TEST FIXTURES — NOT real leads/agencies.
  // Added manually (not by scripts/import-leads.mjs) so the two C/G
  // seller-ask journey branches resolve an identity for manual review. Their
  // probe/evidence/grade/communications data is self-contained, served
  // entirely by api/novus/demo-state.js (see DEV_TEST_SLUG_C_ASK /
  // DEV_TEST_SLUG_G_NO_ASK there) — neither touches the real
  // PROBES/INTELLIGENCE/COMMUNICATIONS Google Sheet, so they cannot
  // contaminate any real agency. TO REMOVE: delete both entries AND the
  // matching blocks in api/novus/demo-state.js. A future re-run of
  // scripts/import-leads.mjs will also silently drop these (it only writes
  // real CSV-sourced leads) — re-add by hand if that happens first.
  "test-c1-fast-response": {
    "company": "NOVUS Test Agency — Seller Ask (DEV ONLY)",
    "url": "",
    "town": "Demo Town",
    "first_name": "",
    "phone": "",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "test-g-no-ask": {
    "company": "NOVUS Test Agency — Seller No-Ask (DEV ONLY)",
    "url": "",
    "town": "Demo Town",
    "first_name": "",
    "phone": "",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  // ═══════════════════════════════════════════════════════════════════════
  "ashton-white-dxfw": {
    "company": "Ashton White Estate Agents Billericay",
    "url": "http://www.ashtonwhite.co.uk/?%20utm_source=GoogleMyBusiness&utm_medium=organic&utm_campaign=GMB&utm_term=location&utm_content=location",
    "town": "Billericay",
    "first_name": "",
    "phone": "01277 659002",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://ashtonwhite.co.uk/property/laindon-common-road-little-burstead-billericay-6/"
  },
  "stanton-hockett-3n81": {
    "company": "Stanton Hockett Limited",
    "url": "http://www.stantonhockett.co.uk/",
    "town": "Billericay",
    "first_name": "Bradley",
    "phone": "01277 714777",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.stantonhockett.co.uk/property/flat-8-bricklayers-court-61-hadham-road-bishops-stortford-cm12-2qy/a0733bf4-c241-4245-859c-ad2e3c075638"
  },
  "quirks-estate-7dxl": {
    "company": "Quirks Estate Agents Billericay",
    "url": "https://www.quirkandpartners.co.uk/",
    "town": "Billericay",
    "first_name": "",
    "phone": "01277 626541",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://quirkandpartners.co.uk/property/laindon-common-road-little-burstead-billericay/"
  },
  "henton-kirkman-nu7n": {
    "company": "Henton Kirkman Residential",
    "url": "https://www.hentonkirkman.co.uk/",
    "town": "Billericay",
    "first_name": "",
    "phone": "01277 500800",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "parabar-estates-o46o": {
    "company": "ParaBar Estates",
    "url": "http://www.parabar.co.uk/",
    "town": "Billericay",
    "first_name": "",
    "phone": "01277 656563",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://parabar.co.uk/property/mountnessing-road-billericay-2/"
  },
  "tyler-estates-jiya": {
    "company": "Tyler Estates",
    "url": "http://www.tylerestates.co.uk/",
    "town": "Billericay",
    "first_name": "Jeremy",
    "phone": "01277 626181",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.tylerestates.co.uk/property/1-bed-retirement-property-for-sale-in-outwood-common-road-billericay-cm11/625002"
  },
  "the-property-77zi": {
    "company": "The Property Specialists | Estate agents in Billericay",
    "url": "https://www.thepropertyspecialists.co.uk/?utm_source=localmaps&utm_medium=gbp&utm_campaign=billericay",
    "town": "Billericay",
    "first_name": "David",
    "phone": "01277 654446",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "gibson-brennan-76vf": {
    "company": "Gibson & Brennan Estate Agents",
    "url": "http://www.gibsonandbrennan.co.uk/",
    "town": "Billericay",
    "first_name": "Jake",
    "phone": "01268 219992",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "crown-estate-n4id": {
    "company": "Crown Estate Agents",
    "url": "https://www.crownestatesagents.co.uk/",
    "town": "Billericay",
    "first_name": "",
    "phone": "01268 711133",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "chalmers-agency-mevq": {
    "company": "Chalmers Agency",
    "url": "https://www.chalmers-agency.co.uk/",
    "town": "Billericay",
    "first_name": "Mandy",
    "phone": "01277 840917",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "carter-remy-hpo7": {
    "company": "Carter Remy Estate Agents",
    "url": "http://www.carterremy.co.uk/",
    "town": "Billericay",
    "first_name": "",
    "phone": "01268 727757",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://carterremy.co.uk/property/bowers-court-drive-bowers-gifford/"
  },
  "period-homes-wgjx": {
    "company": "Period Homes Essex",
    "url": "http://www.periodhomes.co.uk/",
    "town": "Billericay",
    "first_name": "",
    "phone": "01277 288000",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "crowsheath-estate-3u3n": {
    "company": "Crowsheath Estate",
    "url": "https://crowsheathestate.co.uk/",
    "town": "Billericay",
    "first_name": "",
    "phone": "01277 523422",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "wn-properties-sz3p": {
    "company": "WN Properties",
    "url": "http://www.wnproperties.co.uk/",
    "town": "Billericay",
    "first_name": "Zaman",
    "phone": "01277 225191",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.wnproperties.co.uk/properties-for-sale/property/12854284-church-road-ramsden-bellhouse-billericay"
  },
  "keith-ashton-sel6": {
    "company": "Keith Ashton Estate Agents",
    "url": "https://www.keithashton.co.uk/",
    "town": "Brentwood",
    "first_name": "",
    "phone": "01277 260858",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.keithashton.co.uk/property/the-windmill-cottage-mill-lane-high-ongar-ongar/"
  },
  "hs-estate-3wuj": {
    "company": "HS Estate Agents",
    "url": "http://www.hs-estateagents.co.uk/",
    "town": "Brentwood",
    "first_name": "Fran",
    "phone": "01277 220819",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "meacock-jones-unk7": {
    "company": "Meacock & Jones",
    "url": "http://www.meacockjones.co.uk/",
    "town": "Brentwood",
    "first_name": "Russell",
    "phone": "01277 218485",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.meacockjones.co.uk/property/childerditch-street-little-warley-cm13/meaco-001098/1"
  },
  "tinsley-co-w98u": {
    "company": "Tinsley & Co.",
    "url": "https://www.tinsleys.co.uk/",
    "town": "Brentwood",
    "first_name": "Ian",
    "phone": "01277 781030",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.tinsleys.co.uk/property/area-guides/ingatestone"
  },
  "hardings-lettings-f5it": {
    "company": "Hardings Lettings & Property Management Ltd",
    "url": "http://www.hardingslettings.co.uk/",
    "town": "Brentwood",
    "first_name": "Robert",
    "phone": "01277 509644",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "smooth-move-wews": {
    "company": "Smooth Move",
    "url": "http://www.smoothmoveestates.co.uk/",
    "town": "Brentwood",
    "first_name": "Gary",
    "phone": "01277 600700",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://smoothmoveestates.co.uk/property/fontwell-park-gardens-hornchurch/"
  },
  "blueprint-property-88hj": {
    "company": "Blueprint Property Group Ltd",
    "url": "https://www.blueprintproperties.co.uk/",
    "town": "Brentwood",
    "first_name": "",
    "phone": "01277 287931",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.blueprintproperties.co.uk/property/2041-exclusive-collection-of-five-stunning-country-barns"
  },
  "freehold-sale-6dag": {
    "company": "Freehold Sale",
    "url": "https://www.freehold-sale.co.uk/",
    "town": "Brentwood",
    "first_name": "Adam",
    "phone": "01245 227920",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "parry-cohen-mgux": {
    "company": "Parry Cohen Estate Agents",
    "url": "http://www.parrycohen.co.uk/",
    "town": "Shenfield",
    "first_name": "Richard",
    "phone": "01277 224847",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "farsons-property-5xw4": {
    "company": "Farsons Property Group",
    "url": "https://www.farsonspropertygroup.com/",
    "town": "Shenfield",
    "first_name": "Jacob",
    "phone": "01277 288850",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://farsonspropertygroup.com/properties/for-sale/page/2"
  },
  "mccartney-letting-ic60": {
    "company": "McCartney Letting and Estate Agents in Chelmsford",
    "url": "https://www.mccartneyestateagents.co.uk/?utm_source=localmaps&utm_medium=gbp&utm_campaign=chelmsford",
    "town": "Chelmsford",
    "first_name": "",
    "phone": "01245 266980",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.mccartneyestateagents.co.uk/property/509-brimfield-road-watts-wood-purfleet-essex-rm19-1rq"
  },
  "home-partnership-ppav": {
    "company": "HOME Partnership Estate Agent Chelmsford",
    "url": "http://www.thehomepartnership.co.uk/",
    "town": "Chelmsford",
    "first_name": "Scott",
    "phone": "01245 250222",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.thehomepartnership.co.uk/property/brook-end-road-north-chancellor-park-chelmsford/"
  },
  "charles-david-wvt6": {
    "company": "Charles David Casson Estate Agents Chelmsford",
    "url": "https://www.charlesdavidcasson.co.uk/",
    "town": "Chelmsford",
    "first_name": "Matt",
    "phone": "01245 835859",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.charlesdavidcasson.co.uk/property/donald-way-moulsham-lodge-investors-only/"
  },
  "kiln-and-p4gi": {
    "company": "Kiln and Lodge Estates",
    "url": "http://www.kilnandlodgeestates.co.uk/",
    "town": "Chelmsford",
    "first_name": "",
    "phone": "01245 330764",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "prime-property-t83v": {
    "company": "Prime Property Lettings Ltd T/A Chelmsford Rooms to Rent",
    "url": "http://www.chelmsfordroomstorent.co.uk/",
    "town": "Chelmsford",
    "first_name": "",
    "phone": "01245 356039",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "property-sale-nayq": {
    "company": "Property Sale Now",
    "url": "http://www.propertysalenow.co.uk/",
    "town": "Chelmsford",
    "first_name": "",
    "phone": "01245 955070",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "ob-property-88b1": {
    "company": "OB Property Ltd",
    "url": "http://www.obproperty.co.uk/",
    "town": "Chelmsford",
    "first_name": "Nicola",
    "phone": "01245 202579",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "clive-emson-8ss4": {
    "company": "Clive Emson Land & Property Auctioneers Essex",
    "url": "https://www.cliveemson.co.uk/properties/essex/?utm_source=google&utm_medium=organic&utm_campaign=gmb",
    "town": "Chelmsford",
    "first_name": "",
    "phone": "01245 205778",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.cliveemson.co.uk/properties/essex/properties/essex/clacton-on-sea/"
  },
  "hamilton-piers-5s22": {
    "company": "Hamilton Piers of Springfield & Chelmsford",
    "url": "http://www.hamiltonpiers.co.uk/",
    "town": "Chelmsford",
    "first_name": "",
    "phone": "01245 269777",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "cowling-payne-anwi": {
    "company": "Cowling & Payne Estate Agents Wickford",
    "url": "http://www.cowlingandpayne.co.uk/",
    "town": "Wickford",
    "first_name": "",
    "phone": "01268 730707",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "temme-english-md4m": {
    "company": "Temme English Estate Agents Wickford",
    "url": "http://temmeenglish.co.uk/",
    "town": "Wickford",
    "first_name": "",
    "phone": "01268 573035",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://temmeenglish.co.uk/property/property-portfolio-for-sale-nine-flats-one-bungalow-available-with-tenants-in-situ/"
  },
  "your-home-kyo2": {
    "company": "Your Home Property Management Ltd",
    "url": "https://www.yourhomepm.co.uk/",
    "town": "Wickford",
    "first_name": "James",
    "phone": "01277 812905",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "dixsons-residential-h8eo": {
    "company": "Dixsons Residential Estates Ltd",
    "url": "https://www.dixsonsestates.co.uk/",
    "town": "Wickford",
    "first_name": "Sally-Anne",
    "phone": "01708 443561",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "roger-bates-jnk9": {
    "company": "Roger Bates Properties",
    "url": "http://rogerbatesproperties.co.uk/",
    "town": "Wickford",
    "first_name": "Roger",
    "phone": "07494 803917",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "barrett-estates-4c8w": {
    "company": "Barrett Estates & Letting Agents Ltd",
    "url": "http://www.barrettestates.com/",
    "town": "Wickford",
    "first_name": "Mike",
    "phone": "01268 774676",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://barrettestates.com/property/4-bed-detached-house-for-sale-in-kelvedon-road-messing-colchester-essex-co5/697087"
  },
  "gilbert-rose-cfpo": {
    "company": "Gilbert & Rose",
    "url": "https://www.gilbertandrose.co.uk/",
    "town": "Wickford",
    "first_name": "",
    "phone": "01702 595225",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://gilbertandrose.co.uk/properties/christchurch-road-southend-on-sea-ss2-1"
  },
  "carter-ward-9ojd": {
    "company": "Carter & Ward",
    "url": "http://www.carterandward.co.uk/",
    "town": "Wickford",
    "first_name": "",
    "phone": "01268 733421",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "elliott-smith-uuoo": {
    "company": "Elliott & Smith",
    "url": "http://elliottandsmith.co.uk/",
    "town": "Rayleigh",
    "first_name": "",
    "phone": "01268 947947",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.elliottandsmith.co.uk/property/30663066/kingswood-crescent-rayleigh-2/"
  },
  "diggins-co-dvai": {
    "company": "Diggins & Co Estate Agents Rayleigh",
    "url": "https://www.digginsandco.com/",
    "town": "Rayleigh",
    "first_name": "Darren",
    "phone": "01268 777200",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "hair-son-8ijy": {
    "company": "Hair & Son Rayleigh",
    "url": "https://hairandson.co.uk/estate-agents-rayleigh/",
    "town": "Rayleigh",
    "first_name": "Laurence",
    "phone": "01268 774316",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://hairandson.co.uk/property/luxury-development-for-the-over-60s-chalkwell-avenue-3/"
  },
  "essex-guild-sdc2": {
    "company": "Essex Guild Homes",
    "url": "https://essexguildhomes.co.uk/",
    "town": "Rayleigh",
    "first_name": "Thomas",
    "phone": "01268 777728",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://essexguildhomes.co.uk/property/southchurch-boulevard-southend-on-sea/"
  },
  "lawrence-antony-t9yu": {
    "company": "Lawrence Antony KW",
    "url": "https://www.kwuk.com/agent/mia-antony/",
    "town": "Rayleigh",
    "first_name": "Mia",
    "phone": "01268 778333",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.kwuk.com/property/newport-road-woburn-sands-milton-keynes-mk17-2/"
  },
  "carters-estates-kbat": {
    "company": "Carters Estates",
    "url": "https://www.cartersestates.co.uk/",
    "town": "Rayleigh",
    "first_name": "",
    "phone": "01268 203579",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "dedman-property-k5tr": {
    "company": "Dedman Property Management",
    "url": "http://www.dedmanpropertymanagement.co.uk/",
    "town": "Rayleigh",
    "first_name": "",
    "phone": "01268 771300",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "essex-countryside-argk": {
    "company": "Essex Countryside Rayleigh Estate Agents",
    "url": "http://www.essexcountryside.com/",
    "town": "Rayleigh",
    "first_name": "Anthony",
    "phone": "01268 748428",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "stuart-thomas-tf3f": {
    "company": "Stuart Thomas Estates",
    "url": "http://www.stestates.co.uk/",
    "town": "Rayleigh",
    "first_name": "Stuart",
    "phone": "01702 558110",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.stestates.co.uk/property/3456-4-bedroom-detached-character-house-for-sale"
  },
  "bear-estate-gxpv": {
    "company": "Bear Estate Agents",
    "url": "http://www.bearestateagents.co.uk/",
    "town": "Rayleigh",
    "first_name": "",
    "phone": "01702 416476",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "http://www.bearestateagents.co.uk/for-sale/great-knightleys/208223/"
  },
  "shore-sales-wjgb": {
    "company": "Shore Sales & Lettings",
    "url": "http://www.shore-property.co.uk/",
    "town": "Rayleigh",
    "first_name": "David",
    "phone": "01702 840036",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.shore-property.co.uk/properties/property/810/2-bed-flat-for-sale-burnt-oak-lodge-london-road-hadleigh-hadleigh-benfleet/"
  },
  "arkasian-property-q5oj": {
    "company": "Arkasian Property Management Limited",
    "url": "https://www.arkasian.co.uk/",
    "town": "Rayleigh",
    "first_name": "",
    "phone": "0330 123 0135",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "whirledge-nott-a99i": {
    "company": "Whirledge & Nott Ltd",
    "url": "http://www.whirledgeandnott.co.uk/",
    "town": "Rayleigh",
    "first_name": "Michael",
    "phone": "01268 783377",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "oakmont-property-fiwr": {
    "company": "Oakmont Property Consultants Ltd (Hornchurch Estate Agents)",
    "url": "http://www.oakmontpropertyconsultants.co.uk/",
    "town": "Hornchurch",
    "first_name": "",
    "phone": "01708 223344",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "noble-residential-lgvy": {
    "company": "Noble Residential",
    "url": "https://www.nobleresidential.co.uk/",
    "town": "Hornchurch",
    "first_name": "",
    "phone": "01708 963063",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.nobleresidential.co.uk/property/residential/for-sale/hertfordshire/bishops-stortford/great-hallingbury/bedlars-green/34301837"
  },
  "davis-estates-3toa": {
    "company": "Davis Estates",
    "url": "http://www.davisestates.co.uk/",
    "town": "Hornchurch",
    "first_name": "",
    "phone": "01708 476666",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.davisestates.co.uk/property/2276/3-bed-semi-detached-house-for-sale-squirrels-heath-lane-ardleigh-green-hornchurch-rm11/"
  },
  "100-key-1jfi": {
    "company": "100 Key Properties",
    "url": "http://www.100keyproperties.co.uk/",
    "town": "Hornchurch",
    "first_name": "Andrea",
    "phone": "020 3583 1311",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "stephen-james-n8x1": {
    "company": "Stephen James | Residential & Commercial Estate and Letting Agents in Emerson Park, Hornchurch",
    "url": "https://www.sjlettingandsales.com/",
    "town": "Hornchurch",
    "first_name": "Stephen",
    "phone": "07768 585551",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.sjlettingandsales.com/property/kingsley-gardens-hornchurch-london-rm11-4-bed-semi-detached/"
  },
  "readings-property-7pxz": {
    "company": "Readings Property Services",
    "url": "http://readingspropertyservices.websites.propertylogic.net/",
    "town": "Hornchurch",
    "first_name": "",
    "phone": "01708 437766",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "steve-barton-qcgr": {
    "company": "Steve Barton Estate Agent, Hornchurch, Upminster, Rainham, Gidea Park, Collier Row, Harold Wood, Cranham, Romford.",
    "url": "https://stevebarton.exp.uk.com/",
    "town": "Hornchurch",
    "first_name": "Steve",
    "phone": "01708 985995",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://stevebarton.exp.uk.com/property/fortius-apartments-tredegar-road-london-e3/1431483/"
  },
  "landmark-residential-ejda": {
    "company": "Landmark Residential",
    "url": "http://www.landmarkresidential.co.uk/",
    "town": "Hornchurch",
    "first_name": "Gavin",
    "phone": "020 3195 7610",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://landmarkresidential.co.uk/property/freeman-close-castle-hill-ebbsfleet-valley-2/"
  },
  "alternative-property-2ohi": {
    "company": "Alternative Property Services Letting Agents in Hornchurch",
    "url": "https://alternativepropertyservices.co.uk/?utm_source=localmaps&utm_medium=gbp&utm_campaign=Hornchurch",
    "town": "Hornchurch",
    "first_name": "",
    "phone": "01708 454121",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://alternativepropertyservices.co.uk/property/waterwell-court-manor-avenue-hornchurch-essex-5/"
  },
  "apple-property-h02z": {
    "company": "Apple Property Services",
    "url": "http://www.applepropertyservices.com/",
    "town": "Hornchurch",
    "first_name": "David",
    "phone": "01708 704768",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.applepropertyservices.com/property/sitemap.xml"
  },
  "gates-parish-b7p4": {
    "company": "Gates Parish | Griffin Residential Group",
    "url": "https://www.griffingroup.co.uk/estate-agents/gates-parish-and-co/",
    "town": "Upminster",
    "first_name": "Alan",
    "phone": "01708 250033",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "bowyer-mark-lf0j": {
    "company": "Bowyer Mark",
    "url": "https://markbowyerestateagents.co.uk/",
    "town": "Upminster",
    "first_name": "Mark",
    "phone": "01708 220077",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://markbowyerestateagents.co.uk/properties/huskards-waldergrave-gardens-upminster/"
  },
  "gates-parish-3gw6": {
    "company": "Gates Parish & Co",
    "url": "https://www.gates-parish.co.uk/",
    "town": "Upminster",
    "first_name": "Alan",
    "phone": "01708 250033",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "abbey-estate-2fql": {
    "company": "Abbey Estate Agents",
    "url": "http://www.abbey-homes.co.uk/",
    "town": "Upminster",
    "first_name": "",
    "phone": "01708 554672",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "m-p-313a": {
    "company": "M&P Estates",
    "url": "https://www.mpestates.co.uk/?utm_source=localmaps&utm_medium=gbp&utm_campaign=south_ockendon",
    "town": "Upminster",
    "first_name": "",
    "phone": "01708 851999",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://mpestates.co.uk/properties/3-bedroom-flats-apartments-house-for-sale-in-corran-way-south-ockendon-essex-rm15/535415"
  },
  "barringtons-property-wx1t": {
    "company": "Barringtons Property Consultants",
    "url": "http://www.barringtonsproperty.co.uk/",
    "town": "Ingatestone",
    "first_name": "Mark",
    "phone": "01277 600400",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "walkers-people-qcle": {
    "company": "Walkers, People & Property",
    "url": "https://www.walkersestates.co.uk/",
    "town": "Ingatestone",
    "first_name": "",
    "phone": "01277 355005",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "shugi-estates-abr8": {
    "company": "Shugi Estates",
    "url": "http://www.shugiestates.com/",
    "town": "Ingatestone",
    "first_name": "",
    "phone": "01245 830250",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "holden-estate-h386": {
    "company": "Holden Estate Agents",
    "url": "http://www.holdenestates.co.uk/",
    "town": "Maldon",
    "first_name": "Ryan",
    "phone": "01621 841011",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "ardent-estates-4w3e": {
    "company": "Ardent Estates",
    "url": "http://www.ardentestates.co.uk/",
    "town": "Maldon",
    "first_name": "Paul",
    "phone": "01621 851014",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "maldon-lettings-44bw": {
    "company": "MALDON LETTINGS LIMITED",
    "url": "http://www.maldonlettings.co.uk/",
    "town": "Maldon",
    "first_name": "Claire",
    "phone": "01621 850145",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "keymann-residential-ed5b": {
    "company": "KeyMann Residential Lettings Ltd",
    "url": "http://www.keymann.co.uk/",
    "town": "Maldon",
    "first_name": "John",
    "phone": "01621 855994",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://keymann.co.uk/property/33-strawberry-lane-tolleshunt-knights-maldon-essex-co5-0rx/"
  },
  "starting-point-d4gk": {
    "company": "Starting Point Residential",
    "url": "https://startingpointresidential.co.uk/",
    "town": "Maldon",
    "first_name": "Joe",
    "phone": "01621 488321",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "keeleys-lettings-nh4s": {
    "company": "Keeleys Lettings Agent & Property Management in Maldon",
    "url": "https://www.keeleysessex.co.uk/?utm_source=localmaps&utm_medium=gbp&utm_campaign=Maldon",
    "town": "Maldon",
    "first_name": "",
    "phone": "01621 842444",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "david-martin-i8su": {
    "company": "David Martin Estate Agents Ltd",
    "url": "http://www.dmgtiptree.co.uk/",
    "town": "Maldon",
    "first_name": "David",
    "phone": "01621 815815",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://dmgtiptree.co.uk/property/rosemary-court-rectory-road-tiptree-essex-2/"
  },
  "curtis-o-h510": {
    "company": "Curtis O'Boyle",
    "url": "http://www.curtisoboyle.co.uk/",
    "town": "Maldon",
    "first_name": "Anthony",
    "phone": "01621 855558",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "john-alexander-87le": {
    "company": "John Alexander Estate Agents & Letting Agents Tiptree",
    "url": "http://www.john-alexander.co.uk/",
    "town": "Maldon",
    "first_name": "Craig",
    "phone": "01621 814334",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "hardy-king-z6j9": {
    "company": "Hardy-King Estate Agents",
    "url": "http://www.hardy-king.com/",
    "town": "Maldon",
    "first_name": "Craig",
    "phone": "01621 834110",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.hardy-king.com/property/margery-allingham-place-tolleshunt-darcy-2/"
  },
  "game-estate-5str": {
    "company": "Game Estate Agents Ltd",
    "url": "http://www.game-estates.co.uk/",
    "town": "Maldon",
    "first_name": "",
    "phone": "01621 869986",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.game-estates.co.uk/property/1870-3bedroom-park-home-for-sale"
  },
  "hibbert-foy-lai4": {
    "company": "Hibbert-Foy Property",
    "url": "https://hibbertfoyproperty.co.uk/",
    "town": "Maldon",
    "first_name": "Reuben",
    "phone": "01621 731697",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "right-buy-tgei": {
    "company": "Right Buy Homes",
    "url": "http://www.rightbuyhomes.com/",
    "town": "Maldon",
    "first_name": "Steve",
    "phone": "020 3322 8097",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.rightbuyhomes.com/index.php/properties/global-alternative-investments"
  },
  "the-healthcare-4uxh": {
    "company": "The Healthcare Property Company Limited",
    "url": "http://www.thehealthcarepropertycompany.co.uk/",
    "town": "Maldon",
    "first_name": "",
    "phone": "020 3617 8730",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "harris-and-sc0t": {
    "company": "Harris and Wood Witham",
    "url": "https://harrisandwood.co.uk/",
    "town": "Witham",
    "first_name": "",
    "phone": "01376 780222",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://harrisandwood.co.uk/properties/3-bedroom-house-house-for-sale-in-the-saffron-(plot-17)-off-coopers-crescent-west-bergholt-colchester-co6/536238"
  },
  "yaxley-homes-g5yv": {
    "company": "Yaxley Homes",
    "url": "http://www.yaxleyhomes.co.uk/",
    "town": "Witham",
    "first_name": "Ricky",
    "phone": "01376 519092",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.yaxleyhomes.co.uk/property/1003/?propInd=S&"
  },
  "witlet-q9bi": {
    "company": "WitLet",
    "url": "http://www.witlet.co.uk/",
    "town": "Witham",
    "first_name": "",
    "phone": "01376 502500",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.witlet.co.uk/property/orchard-gardens-colchester/"
  },
  "baker-estates-em8x": {
    "company": "Baker Estates Essex",
    "url": "http://www.baker-estates.co.uk/",
    "town": "Witham",
    "first_name": "",
    "phone": "01621 333765",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://baker-estates.co.uk/property/shirebourn-vale-south-woodham-ferrers-chelmsford/"
  },
  "brink-riley-dypi": {
    "company": "Brink Riley Properties Ltd",
    "url": "http://www.brinkriley.co.uk/",
    "town": "Witham",
    "first_name": "Natalie",
    "phone": "01376 510669",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "riverside-estates-sv3y": {
    "company": "Riverside Estates",
    "url": "http://www.riversideestates.co.uk/",
    "town": "Witham",
    "first_name": "",
    "phone": "01376 571111",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.riversideestates.co.uk/property/attractive-four-bed-linked-detached-family-house-widgeon-place-kelvedon-colchester-essex/"
  },
  "witham-auctions-okhn": {
    "company": "Witham Auctions",
    "url": "https://www.withamauctions.co.uk/",
    "town": "Witham",
    "first_name": "",
    "phone": "07561 187318",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "boydens-west-8i3e": {
    "company": "Boydens West Essex Branch, Kelvedon",
    "url": "https://www.boydens.co.uk/branches/west-essex",
    "town": "Witham",
    "first_name": "Jules",
    "phone": "01376 570335",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.boydens.co.uk/sales/selling-guide"
  },
  "heritage-estate-vzkx": {
    "company": "Heritage Estate Agents",
    "url": "http://www.essexheritage.co.uk/",
    "town": "Witham",
    "first_name": "",
    "phone": "01376 566890",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.essexheritage.co.uk/properties/letting/uncategorized/uncategorized/halstead-2/"
  },
  "just-recruitment-u4mv": {
    "company": "Just Recruitment Group Ltd",
    "url": "https://justrecruitment.co.uk/",
    "town": "Witham",
    "first_name": "Jenny",
    "phone": "01376 517079",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "southfields-copb": {
    "company": "Southfields",
    "url": "https://www.beechgrovehomes.co.uk/property-developments/witham-southfields?utm_source=google_my_business&utm_medium=knowledge_graph",
    "town": "Witham",
    "first_name": "",
    "phone": "01376 230367",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "branocs-estates-nzah": {
    "company": "Branocs Estates",
    "url": "http://www.branocsestates.co.uk/",
    "town": "Braintree",
    "first_name": "Tristan",
    "phone": "01376 386555",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.branocsestates.co.uk/property/34852274-denton-crescent-black-notley-braintree/"
  },
  "michaels-property-0yjt": {
    "company": "Michaels Property Consultants Braintree",
    "url": "https://www.michaelsproperty.co.uk/branches/braintree",
    "town": "Braintree",
    "first_name": "Patrick",
    "phone": "01376 337400",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.michaelsproperty.co.uk/property/list/forsale"
  },
  "joscelyne-chase-o1ti": {
    "company": "Joscelyne Chase",
    "url": "http://www.joscelynechase.co.uk/",
    "town": "Braintree",
    "first_name": "",
    "phone": "01376 322222",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "katrina-barnes-i6ls": {
    "company": "Katrina Barnes",
    "url": "https://katrinabarnes.exp.uk.com/",
    "town": "Braintree",
    "first_name": "Katrina",
    "phone": "07508 844430",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://katrinabarnes.exp.uk.com/property/broadoaks-crescent-kings-park-braintree/1262246/"
  },
  "gateway-residential-d5tv": {
    "company": "Gateway Residential Sales & Lettings Ltd",
    "url": "http://www.gatewaypropertyuk.com/",
    "town": "Braintree",
    "first_name": "James",
    "phone": "01371 300120",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "centurion-property-pyh1": {
    "company": "Centurion Property Services",
    "url": "http://www.centurion-property.co.uk/",
    "town": "Braintree",
    "first_name": "",
    "phone": "01376 550010",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.centurion-property.co.uk/property/residential/for-sale/essex/sible-hedingham/westrop-drive/BF011561"
  },
  "steven-rich-lfs6": {
    "company": "Steven Rich Property Management LTD",
    "url": "https://www.richproperty.co.uk/",
    "town": "Braintree",
    "first_name": "Steven",
    "phone": "07383 659689",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.richproperty.co.uk/properties/new%7Cspacious-house%7C2-bedrooms%7C5-beds%7C5-guests%7Cwifi"
  },
  "gray-co-ac7a": {
    "company": "Gray & Co",
    "url": "http://www.grayandcompany.co.uk/",
    "town": "Braintree",
    "first_name": "",
    "phone": "01371 810154",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "http://www.grayandcompany.co.uk/property/uploaded/CMPMemberShipCertificate.pdf"
  },
  "grange-property-aiso": {
    "company": "GRANGE PROPERTY SERVICES LTD",
    "url": "http://www.grangeproperty.co.uk/",
    "town": "Braintree",
    "first_name": "Fiona",
    "phone": "01245 360715",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.grangeproperty.co.uk/properties-for-sale/property/94-coggeshall-road-braintree"
  },
  "mulberry-homes-hl7w": {
    "company": "Mulberry Homes at Braintree",
    "url": "https://mulberryhomes.co.uk/developments/mulberry-homes-at-braintree/overview/",
    "town": "Braintree",
    "first_name": "",
    "phone": "0333 121 1060",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "kingswood-estate-cfjm": {
    "company": "Kingswood Estate Agents Basildon",
    "url": "http://www.kingswoodbasildon.com/",
    "town": "Basildon",
    "first_name": "Max",
    "phone": "01268 272222",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://kingswoodbasildon.com/property/reeves-close-langdon-hills-basildon-essex-ss16-6pd/"
  },
  "lara-bradley-8bew": {
    "company": "Lara Bradley Estate Agent",
    "url": "https://iad.uk.com/real-estate-agent/lara.bradley",
    "town": "Basildon",
    "first_name": "Lara",
    "phone": "07795 002226",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "daniel-property-koql": {
    "company": "Daniel Property Group",
    "url": "https://danielproperty.co.uk/",
    "town": "Basildon",
    "first_name": "Daniel",
    "phone": "07534 550339",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "gecko-estate-1t2o": {
    "company": "Gecko Estate Agents Ltd",
    "url": "http://www.geckoproperty.co.uk/",
    "town": "Basildon",
    "first_name": "",
    "phone": "01268 426196",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "essex-properties-ogw2": {
    "company": "Essex Properties Limited",
    "url": "https://www.essexproperties.co.uk/",
    "town": "South Woodham Ferrers",
    "first_name": "",
    "phone": "01245 329652",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.essexproperties.co.uk/property/tylers-ride-south-woodham-ferrers-essex/"
  },
  "nbs-properties-hdzr": {
    "company": "NBS Properties LLP",
    "url": "http://nbscommprops.com/",
    "town": "South Woodham Ferrers",
    "first_name": "",
    "phone": "07881 785626",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "williams-and-1xxm": {
    "company": "Williams And Donovan Hockley Sales",
    "url": "https://www.williamsanddonovan.com/branches/hockley",
    "town": "South Woodham Ferrers",
    "first_name": "",
    "phone": "01702 200666",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.williamsanddonovan.com/properties/sales/most-recent-first"
  },
  "hall-s-v245": {
    "company": "Hall's Property Group",
    "url": "http://www.hallspropertygroup.co.uk/",
    "town": "Great Baddow",
    "first_name": "Samm",
    "phone": "01708 875088",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.hallspropertygroup.co.uk/property/flat-crick-court-spring-place-barking-rs0036/"
  },
  "mary-bugg-iqdy": {
    "company": "Mary Bugg Powered By eXp",
    "url": "http://marybugg.exp.uk.com/",
    "town": "Great Baddow",
    "first_name": "Mary",
    "phone": "01245 948484",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://marybugg.exp.uk.com/property/mill-lane-broomfield-chelmsford-cm1-7bq/1475502/"
  },
  "elwell-taylor-vqxv": {
    "company": "Elwell Taylor",
    "url": "http://www.elwelltaylor.co.uk/",
    "town": "Great Baddow",
    "first_name": "Adam",
    "phone": "01245 266088",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.elwelltaylor.co.uk/property/instagram.com/elwell_taylor/"
  },
  "domans-residential-u2pm": {
    "company": "Domans Residential Ltd",
    "url": "https://www.domansresidential.co.uk/",
    "town": "Great Baddow",
    "first_name": "",
    "phone": "01245 981222",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "cooper-hirst-d1it": {
    "company": "Cooper Hirst Ltd",
    "url": "https://www.cooper-hirst.com/",
    "town": "Great Baddow",
    "first_name": "",
    "phone": "01245 258141",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "luux-venture-jr52": {
    "company": "Luux Venture Group",
    "url": "https://www.luuxventuregroup.com/",
    "town": "Great Baddow",
    "first_name": "",
    "phone": "020 3051 0210",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.luuxventuregroup.com/properties/3-bedroom-detached-house-for-sale/"
  },
  "colubrid-estate-n1j8": {
    "company": "Colubrid Estate Agents",
    "url": "http://www.colubrid.co.uk/",
    "town": "Great Baddow",
    "first_name": "Andrew",
    "phone": "01245 976936",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://colubrid.co.uk/property/blackbush-lane-horndon-on-the-hill/"
  },
  "kemsley-llp-g0l0": {
    "company": "Kemsley LLP",
    "url": "http://www.kemsley.com/",
    "town": "Great Baddow",
    "first_name": "Tim",
    "phone": "01245 358988",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "garrington-property-koy3": {
    "company": "Garrington Property Finders",
    "url": "https://www.garringtonsoutheast.co.uk/",
    "town": "Great Baddow",
    "first_name": "",
    "phone": "01245 905377",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "national-trust-i9xy": {
    "company": "National Trust",
    "url": "https://www.nationaltrust.org.uk/danbury-commons-and-blakes-wood",
    "town": "Danbury",
    "first_name": "",
    "phone": "01245 227662",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "danbury-ridge-pdei": {
    "company": "Danbury Ridge Wine Estate",
    "url": "http://www.danburyridge.com/",
    "town": "Danbury",
    "first_name": "Michael",
    "phone": "",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "cheffins-newmarket-cmj2": {
    "company": "Cheffins Newmarket",
    "url": "https://www.cheffins.co.uk/residential/offices-contacts/newmarket.htm",
    "town": "Stock",
    "first_name": "",
    "phone": "01638 663228",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.cheffins.co.uk/properties/burroughs-green.htm"
  },
  "pocock-shaw-m31t": {
    "company": "Pocock + Shaw",
    "url": "https://www.pocock.co.uk/",
    "town": "Stock",
    "first_name": "",
    "phone": "01638 668284",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "david-burr-tfbj": {
    "company": "David Burr Newmarket",
    "url": "https://davidburr.co.uk/our-locations/newmarket/",
    "town": "Stock",
    "first_name": "Nick",
    "phone": "01638 669035",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://davidburr.co.uk/property/burwell-cambridge-cambridgeshire-3/"
  },
  "ensum-brown-ex9i": {
    "company": "Ensum Brown Estate Agents Newmarket",
    "url": "https://ensumbrown.com/newmarket-sales/",
    "town": "Stock",
    "first_name": "Neil",
    "phone": "01638 280030",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://ensumbrown.com/property/princes-mews-carrington-court-princes-mews-sg8-3/"
  },
  "morris-armitage-wg41": {
    "company": "Morris Armitage Estate Agents Newmarket",
    "url": "http://www.morrisarmitage.co.uk/",
    "town": "Stock",
    "first_name": "Simon",
    "phone": "01638 560221",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://morrisarmitage.co.uk/property/wellington-close-chedburgh-bury-st-edmunds/"
  },
  "tylers-estate-1rwa": {
    "company": "Tylers Estate Agents and Residential Lettings",
    "url": "http://www.tylers.net/",
    "town": "Stock",
    "first_name": "",
    "phone": "01638 660303",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.tylers.net/properties/22005853/sales/HIS100276"
  },
  "lee-wilkinson-uevj": {
    "company": "Lee Wilkinson Estate Agents Ltd",
    "url": "https://www.leewilkinson.exp.uk.com/",
    "town": "Stock",
    "first_name": "Lee",
    "phone": "01440 979980",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "countryside-estates-q72g": {
    "company": "Countryside Estates",
    "url": "http://www.countrysideestates.co.uk/",
    "town": "Benfleet",
    "first_name": "",
    "phone": "01268 755555",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.countrysideestates.co.uk/properties-for-sale/property/362-lowlands-road-hullbridge-hockley"
  },
  "aspire-estate-aus5": {
    "company": "Aspire Estate Agents",
    "url": "http://www.aspireestateagents.co.uk/",
    "town": "Benfleet",
    "first_name": "Edward",
    "phone": "01268 777400",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "morgan-brookes-2cp4": {
    "company": "Morgan Brookes",
    "url": "http://www.morganbrookes.co.uk/",
    "town": "Benfleet",
    "first_name": "Nicole",
    "phone": "01268 755626",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://morganbrookes.co.uk/property/forest-view-london-road-benfleet/"
  },
  "fisks-ltd-d8u5": {
    "company": "Fisks Ltd",
    "url": "http://www.fisks.co.uk/",
    "town": "Benfleet",
    "first_name": "John",
    "phone": "01268 565555",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "robert-michael-zuab": {
    "company": "Robert Michael Estate Agents",
    "url": "http://www.robertmichael.co.uk/",
    "town": "Benfleet",
    "first_name": "",
    "phone": "01268 753889",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "brown-brand-28l8": {
    "company": "Brown & Brand",
    "url": "http://www.brownbrand.co.uk/",
    "town": "Benfleet",
    "first_name": "Paul",
    "phone": "01702 552966",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.brownbrand.co.uk/properties/letting/uncategorized/benfleet/springfield-benfleet/"
  },
  "richard-poyntz-d7ni": {
    "company": "Richard Poyntz and Co",
    "url": "http://www.richardpoyntz.com/",
    "town": "Benfleet",
    "first_name": "Richard",
    "phone": "01268 699599",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://richardpoyntz.com/essex/canvey-island/sales/from-2-bed/up-to-2-bed"
  },
  "cross-tillett-1oaa": {
    "company": "Cross & Tillett",
    "url": "https://www.crossandtillett.co.uk/",
    "town": "Benfleet",
    "first_name": "Paul",
    "phone": "01268 904777",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "nairnsey-fisher-ud8o": {
    "company": "Nairnsey Fisher & Lewis",
    "url": "http://www.nfl-legal.co.uk/",
    "town": "Benfleet",
    "first_name": "",
    "phone": "01268 566655",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "stephen-lane-o6kg": {
    "company": "Stephen Lane Estate Agents",
    "url": "http://www.stephenlaneestates.co.uk/",
    "town": "Benfleet",
    "first_name": "Stephen",
    "phone": "01268 514777",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": "https://www.stephenlaneestates.co.uk/properties/complaints-procedure/"
  },
  "oakleighblue-bk3q": {
    "company": "OakleighBlue",
    "url": "http://www.oakleighblue.co.uk/",
    "town": "Hockley",
    "first_name": "Keith",
    "phone": "01702 205051",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  },
  "sharp-lettings-wtu0": {
    "company": "Sharp Lettings",
    "url": "https://sharplettings.com/",
    "town": "Hockley",
    "first_name": "",
    "phone": "01702 233064",
    "probe_address": "",
    "probe_sent": "",
    "listing_url": ""
  }
};

export default LEADS;
